// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9rgRyuzaGCbn25Q8wMmnOJIMhkhGi6fo',
    appId: '1:724202877098:web:faeff77c4ff8627e51a0d3',
    messagingSenderId: '724202877098',
    projectId: 'ripple-71db4',
    authDomain: 'ripple-71db4.firebaseapp.com',
    storageBucket: 'ripple-71db4.firebasestorage.app',
    measurementId: 'G-VEZ6FKSG5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv2KzUxbios9qVfbEKqDZxOyGGU_gWFPg',
    appId: '1:724202877098:android:47216cf615dfc9a251a0d3',
    messagingSenderId: '724202877098',
    projectId: 'ripple-71db4',
    storageBucket: 'ripple-71db4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx99NwFQikcDwbCxH6dGV6jjynM8JLvMo',
    appId: '1:724202877098:ios:f321c3a3d39d0ff051a0d3',
    messagingSenderId: '724202877098',
    projectId: 'ripple-71db4',
    storageBucket: 'ripple-71db4.firebasestorage.app',
    iosClientId: '724202877098-a6d482l74mtf7mffcp1r7i7fkm0p7lna.apps.googleusercontent.com',
    iosBundleId: 'com.codechakra.ripple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx99NwFQikcDwbCxH6dGV6jjynM8JLvMo',
    appId: '1:724202877098:ios:f321c3a3d39d0ff051a0d3',
    messagingSenderId: '724202877098',
    projectId: 'ripple-71db4',
    storageBucket: 'ripple-71db4.firebasestorage.app',
    iosClientId: '724202877098-a6d482l74mtf7mffcp1r7i7fkm0p7lna.apps.googleusercontent.com',
    iosBundleId: 'com.codechakra.ripple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9rgRyuzaGCbn25Q8wMmnOJIMhkhGi6fo',
    appId: '1:724202877098:web:762041b69fe853e151a0d3',
    messagingSenderId: '724202877098',
    projectId: 'ripple-71db4',
    authDomain: 'ripple-71db4.firebaseapp.com',
    storageBucket: 'ripple-71db4.firebasestorage.app',
    measurementId: 'G-S6Y7Z8QDPL',
  );
}
